spring.application.name=umufly-api

#### Base de datos
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@hydra-prescan.atica.um.es:1526/ZEUSTEST
spring.datasource.username=FORMACION_TICARUM
spring.datasource.password=FFDghG345

### Logs para ver si reconoce las tablas 
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.orm.boot=TRACE

### REST evitar que se ordenen los JSON alfabeticamente
spring.jackson.mapper.sort-properties-alphabetically=false

### URL servicios MuchoVuelo
umufly.vuelos.providers.muchovuelo.base-url=https://daastest.um.es
umufly.vuelos.providers.muchovuelo.base-path=/ords/zeus/formacion_ticarum/muchovuelo-api/rest/

# Usuario de prueba: prueba@um.es 12345 Prueba Martinez
# Propiedades JWT
jwt.secret=MiSecreT0MuyL4rgoQueTengaAlMenos32Caracteres
jwt.expiration-ms=86400000

#Path donde se expone la documentacion
springdoc.api-docs.path=/api-docs
#Index por defecto
springdoc.swagger-ui.path=/swagger-ui/index.html
#Interfaz grafica habilitada
springdoc.swagger-ui.enabled=true